### ISSUE TITLE
The mAP on IQIYI VID dataset

### ISSUE THREAD

**Issue by chenshen03** [deepinx/iqiyi-vid-challenge#3]
Have you used this code to test mAP on the IQIYI VID dataset?

 What is the result?

**Comment by deepinx** [comment]
This is just a demo code for the IQIYI-VID Challenge. The test mAP is a bit low about 79% because the face recognition model is obtained directly from the insightface model zoo. You can use your own trained models or use multi-model ensemble approaches to improve accuracy.
